version: '3'

services:
  consul:
    image: consul
    environment:
      CONSUL_BIND_INTERFACE: "eth0"
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
    ports:
      - "8500:8500"
    restart: always
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=consul
    networks:
      - rabbit-net

  rabbitmq:
    image: eavictor/rabbitmq-autocluster
    environment:
      AUTOCLUSTER_TYPE: "consul"
      CONSUL_HOST: "consul"
      CONSUL_PORT: "8500"
      CONSUL_SVC: "rabbitmq"
      CONSUL_SVC_ADDR_AUTO: "true"
      AUTOCLUSTER_CLEANUP: "true"
      CLEANUP_WARN_ONLY: "false"
      RABBITMQ_ERLANG_COOKIE: "secrect"
      RABBITMQ_DEFAULT_USER: "eavictor"
      RABBITMQ_DEFAULT_PASS: "mypasswd"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit-net
    restart: unless-stopped
    deploy:
      restart-policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
        window: 120s

networks:
  rabbit-net:
    driver: overlay