version: '3.7'

services:
  consul:
    image: consul
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 3s
        window: 120s
    ports:
      - "8500:8500"
    command: ["agent", "-server", "-bootstrap-expect=3", "-retry-max=10", "-retry-interval=10s", "-datacenter=consul-net", "-join=tasks.consul", "-retry-join=tasks.consul", "-bind={{ GetInterfaceIP \"eth0\" }}", "-client=0.0.0.0", "-ui"]
    networks:
      - rabbit-net

  rabbitmq:
    image: eavictor/rabbitmq_autocluster:3.8.2-management
    depends_on:
      - consul
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Passw0rd
      - RABBITMQ_ERLANG_COOKIE=MYSECRETKEY
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit-net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s

networks:
  rabbit-net:
    driver: overlay
