version: '3.7'

services:
  consul:
    image: consul
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
        order: stop-first
    command: ["agent", "-server", "-bootstrap-expect=3", "-retry-max=3", "-retry-interval=10s", "-datacenter=prod", "-join=consul", "-retry-join=consul", "-bind={{ GetInterfaceIP \"eth0\" }}", "-client=0.0.0.0", "-ui"]
    networks:
      - rabbit-net

  rabbitmq:
    image: eavictor/rabbitmq_autocluster:3.7.15-management
    depends_on:
      - consul
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Passw0rd
      - RABBITMQ_ERLANG_COOKIE=MYSECRETKEY
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit-net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

networks:
  rabbit-net:
    driver: overlay
